### ISSUE TITLE
Error while Building the Project

### ISSUE THREAD

**Issue by Deepansharora27** [salrashid123/gcp_tpm_sealed_keys#1]
Hi, 
I was trying to build the Project, and I was trying to run this command to derive the PCR Value in Read Mode:

`go run pcr_utils/main.go --mode=read --pcr=23 -v 10 -alsologtostderr`

But, I get the following error while trying to build it:

`F0313 15:06:45.723237   58900 main.go:42] can't open TPM %!q(*string=0xc000050f60): stat /dev/tpm0: no such file or directory
goroutine 1 [running]:
github.com/golang/glog.stacks(0x0)
	/Users/deepanshu/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:769 +0x89
github.com/golang/glog.(*loggingT).output(0x1005585e0, 0x3, 0xc00014e3f0, {0x1003dcde5?, 0xc00011bec8?}, 0x2?, 0x0)
	/Users/deepanshu/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:720 +0x46d
github.com/golang/glog.(*loggingT).printf(0xc000050f90?, 0x1?, {0x1002fe32d, 0x15}, {0xc00011bec8, 0x2, 0x2})
	/Users/deepanshu/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:655 +0x10f
github.com/golang/glog.Fatalf(...)
	/Users/deepanshu/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:1148
main.main()
	/Users/deepanshu/Desktop/gcp_tpm_sealed_keys/pcr_utils/main.go:42 +0x1bf
exit status 255
`

Your help will be appreciated on this 
Thanks !!

**Comment by salrashid123** [comment]
The tutorial assumes the tpm device is available at `/dev/tpm0` (which is the path for GCP Shielded VMs)

I'm guessing your trying it out on a mac which i don't really know how to access the TPM on that os.

**Comment by Deepansharora27** [comment]
Aren't we executing this command as a remote user and reading the value from the PCR Bank directly from the GCP VM Instance ?

When you say, access TPM on MacOS, why is that required aren't we directly communicating with the TPM Device on the Remote GCP VM ?

Why do we need to access the TPM on MacOS ?

Please correct me if I am wrong on this

**Comment by salrashid123** [comment]
slightly.

the repo shows a way to seal some data on your laptop and only get it unsealed on a remote VM that has a TPM.

your laptop doesn't need a TPM but it does need the endorsement public key of the remove VM.  How your laptop gets that public key isn't specified here in this repo; the fact that the key was distributed to your laptop by other means is assumed.

once your laptop has the endorsement key, it can seal data such that it can only get decrypted by that same TPM.

the encryption part on yoru laptop can also contain a set of PCR values you expect to be present on the target TPM.  If the PCR values don't match, you can't decrypt.

the command from your original post is

```
go run pcr_utils/main.go --mode=read 
```

is intended to be just read the state of the PCR values on the VM that has the TPM

**Comment by Deepansharora27** [comment]
> slightly.
> 
> the repo shows a way to seal some data on your laptop and only get it unsealed on a remote VM that has a TPM.
> 
> your laptop doesn't need a TPM but it does need the endorsement public key of the remove VM. How your laptop gets that public key isn't specified here in this repo; the fact that the key was distributed to your laptop by other means is assumed.
> 
> once your laptop has the endorsement key, it can seal data such that it can only get decrypted by that same TPM.
> 
> the encryption part on yoru laptop can also contain a set of PCR values you expect to be present on the target TPM. If the PCR values don't match, you can't decrypt.
> 
> the command from your original post is
> 
> ```
> go run pcr_utils/main.go --mode=read 
> ```
> 
> is intended to be just read the state of the PCR values on the VM that has the TPM

One Further Question:

Question :
When you say that the Command is intended to just read the State of the PCR Values on the VM that has the TPM. I am assuming you mean to refer the VM as GCP Remote VM ? 
If that is the Case, then why the Command to Read the PCR Value fails ? 

If you are mentioning the VM as the Laptop(Local Machine), then it is understood that it will fail to read the PCR Value because as you said earlier, path to access the TPM on MacOS is not defined yet

**Comment by salrashid123** [comment]
no, you read the state of the PCR  banks only on the system where the TPM is present.   (when i mentioned VM, i'm talking just about a gcp vm here that has a TPM)

for a GCP Shielded VM, PCR0 happens to be `24af52a4f429b71a3184a6d64cddad17e54ea030e2aa6576bf3a5a3d8bd3328f`

* https://github.com/salrashid123/tpm_key_distribution#server

**Comment by Deepansharora27** [comment]
Then here with the Command that I am executing, why the Build process fails. Because I am able to get the Public Endorsement Key in the First Step and if the read operation is happening from the PCR Bank of the GCP VM, then why it fails ?

**Comment by Deepansharora27** [comment]
Thanks for your Prompt Response 

With your Repo, we can access the TPM on Windows/Linux ?

**Comment by Deepansharora27** [comment]
@salrashid123 Also when we are performing the extend operation on the Remote VM, by updating the PCR 23 Value. On the Console, it shows that the value has been extended successfully and it shows us the new PCR Value for Index 23
But When I visit the Logs for the Remote VM on the console, under the measurements, it does not show me any measurement with the PCR[23] Indice

**Comment by Deepansharora27** [comment]
Also please correct me If I am wrong here but is the `-v` flag used in the Command used to extend the new value that we want into the New PCR Indice ? 
I have noticed that, with both the `read` and the `extend` operation you are using `-v` flag with the `10` value here. So in essence what does this `-v` flag signify ?

**Comment by Deepansharora27** [comment]
@salrashid123 if you could provide Intel about the `-v` flag and it's significance? Why are we using it with both read and extend operation.
I am assuming that v flag is being used to extend a value let's say 10 into a PCR Index . Is this the case of am I misinterpreting ?
